language: c

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - wget http://downloads.sourceforge.net/project/giflib/giflib-5.1.1.tar.bz2
  - tar jxf giflib-5.1.1.tar.bz2
  - (cd giflib-5.1.1; ./configure; make)
  - sudo luarocks install moonscript
  - sudo luarocks install https://luarocks.org/manifests/olivine-labs/busted-2.0.rc7-0.rockspec
  - cat $(which busted) | sed 's/\/usr\/bin\/lua/\/usr\/bin\/luajit-2.0.0-beta9/' > busted
  - chmod +x busted

script: LD_LIBRARY_PATH=giflib-5.1.1/lib/.libs/ ./busted
