name: test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["luajit-openresty", "luajit"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: build
      run: |
        wget https://downloads.sourceforge.net/project/giflib/giflib-6.x/giflib-6.1.3.tar.gz
        tar xzf giflib-6.1.3.tar.gz
        make -C giflib-6.1.3 libgif.so
        luarocks install moonscript
        luarocks install busted
        moonc .

    - name: test
      run: |
        LD_LIBRARY_PATH=giflib-6.1.3/ busted -o utfTerminal

